insert into skill(description,skill_type_id) values('C#',1);
insert into skill(description,skill_type_id) values('Java',1);
insert into skill(description,skill_type_id) values('Phyton',1);
insert into skill(description,skill_type_id) values('Go',1);
insert into skill(description,skill_type_id) values('Javascript',2);
insert into skill(description,skill_type_id) values('Typescript',2);
insert into skill(description,skill_type_id) values('Angular',2);
insert into skill(description,skill_type_id) values('React JS',2);
insert into skill(description,skill_type_id) values('Vue JS',2);
insert into skill(description,skill_type_id) values('JQuery',2);
insert into skill(description,skill_type_id) values('HTML 5',2);
insert into skill(description,skill_type_id) values('CSS',2);
insert into skill(description,skill_type_id) values('SCSS',2);
insert into skill(description,skill_type_id) values('Bootstrap',2);
insert into skill(description,skill_type_id) values('Angular Material',2);
insert into skill(description,skill_type_id) values('Clean Architecture',3);
insert into skill(description,skill_type_id) values('Hexagonal Architecture',3);
insert into skill(description,skill_type_id) values('DDD',3);
insert into skill(description,skill_type_id) values('Microservices',3);
insert into skill(description,skill_type_id) values('SQL Server',4);
insert into skill(description,skill_type_id) values('Oracle',4);
insert into skill(description,skill_type_id) values('Postgre',4);
insert into skill(description,skill_type_id) values('Redis',4);
insert into skill(description,skill_type_id) values('Mongo',4);
insert into skill(description,skill_type_id) values('ETL',5);
insert into skill(description,skill_type_id) values('Power BI',5);
insert into skill(description,skill_type_id) values('Hadoop',5);
insert into skill(description,skill_type_id) values('Linguagem R',5);
insert into skill(description,skill_type_id) values('Github',6);
insert into skill(description,skill_type_id) values('Gitlab',6);
insert into skill(description,skill_type_id) values('PCF',6);
insert into skill(description,skill_type_id) values('Figma',7);
insert into skill(description,skill_type_id) values('Draw.io',7);
insert into skill(description,skill_type_id) values('Scrum',8);
insert into skill(description,skill_type_id) values('Kanban',8);
insert into skill(description,skill_type_id) values('Jira',8);
insert into skill(description,skill_type_id) values('Azure Devops',8);

select * from skill;